version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka1:
    build: .
    ports:
      - "9092"
      - "1099:1099"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    build: .
    ports:
      - "9092"
      - "1098:1098"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka2 -Dcom.sun.management.jmxremote.rmi.port=1098"
      JMX_PORT: 1098
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  machine:
    environment:
     - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
     - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
     - APPDYNAMICS_CONTROLLER_HOST_NAME=ec2-54-202-144-212.us-west-2.compute.amazonaws.com
     - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
     - APPDYNAMICS_CONTROLLER_PORT=8090
     - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=false
     - KAFKA_HOST_1=kafka1
     - KAFKA_PORT_1=1099
     - KAFKA_HOST_2=kafka2
     - KAFKA_PORT_1=1098
     - KAFKA_USERNAME=monitorRole
     - KAFKA_PWD
     - KAKFA_ENCRYPTION_KEY

    build:
      context: .
      dockerfile: Dockerfile_MA
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock