version: '2'
services:
  machine:

    environment:
     - APPDYNAMICS_AGENT_ACCOUNT_NAME=customer1
     - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
     - APPDYNAMICS_CONTROLLER_HOST_NAME=ec2-54-202-144-212.us-west-2.compute.amazonaws.com
     - APPDYNAMICS_CONTROLLER_SSL_ENABLED=false
     - APPDYNAMICS_CONTROLLER_PORT=8090
     - MACHINE_AGENT_PROPERTIES=-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true
     - KAFKA_HOST=host.docker.internal
     - KAFKA_PORT=1099

    build:
      context: .
      dockerfile: Dockerfile_MA
    volumes:
      - /:/hostroot:ro
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: wurstmeister/zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2181:2181"

  kafka:

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092"
      - "1099:1099"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock