FROM vishakasekar/machineagent:latest AS MA
ADD target/KafkaMonitor-*.zip /opt/appdynamics/monitors
RUN unzip -q "/opt/appdynamics/monitors/KafkaMonitor-*.zip" -d /opt/appdynamics/monitors
RUN cp /opt/appdynamics/monitors/KafkaMonitor/config_for_teamcity.yml /opt/appdynamics/monitors/KafkaMonitor/config.yml
RUN find /opt/appdynamics/monitors/ -name '*.zip' -delete
CMD ["sh", "-c", "java ${MACHINE_AGENT_PROPERTIES} -jar /opt/appdynamics/machineagent.jar"]