FROM vishakasekar/machineagent:latest AS MA
ADD target/KafkaMonitor-*.zip /opt/appdynamics/monitors
COPY /src/test/resources/keystore/kafka.client.truststore.jks /opt/appdynamics
RUN unzip -q "/opt/appdynamics/monitors/KafkaMonitor-*.zip" -d /opt/appdynamics/monitors
COPY /src/integration-test/resources/conf/config_ci.yml /opt/appdynamics/monitors/KafkaMonitor/config.yml
CMD ["sh", "-c" , "java -cp "kafka-monitoring-extension.jar" com.appdynamics.extensions.crypto.Encryptor axcdde43535hdhdgfiniyy576 myPassword"]
RUN find /opt/appdynamics/monitors/ -name '*.zip' -delete
CMD ["sh", "-c", "java ${MACHINE_AGENT_PROPERTIES} -jar /opt/appdynamics/machineagent.jar"]