FROM vishakasekar/machineagent:latest AS MA
RUN pwd
ADD target/KafkaMonitor-*.zip /opt/appdynamics/monitors
COPY /src/test/resources/keystore/kafka.client.truststore.jks /opt/appdynamics
RUN unzip -q "/opt/appdynamics/monitors/KafkaMonitor-*.zip" -d /opt/appdynamics/monitors
RUN java -cp "/opt/appdynamics/monitors/KafkaMonitor/kafka-monitoring-extension.jar" com.appdynamics.extensions.crypto.Encryptor axcdde43535hdhdgfiniyy576 QED > tmp.txt
RUN cat tmp.txt
COPY /src/integration-test/resources/conf/config_ci.yml /opt/appdynamics/monitors/KafkaMonitor/config.yml
RUN sed -i "s/old//"$(head -2 tmp.txt | tail -1)"//g" /opt/appdynamics/monitors/KafkaMonitor/config.yml
RUN find /opt/appdynamics/monitors/ -name '*.zip' -delete
CMD ["sh", "-c", "java ${MACHINE_AGENT_PROPERTIES} -jar /opt/appdynamics/machineagent.jar"]
