package KafkaMonitoringExtensionCi.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'd8ec7368-9cde-4a3c-b444-e7c3d06d247a' (id = 'KafkaMonitoringExtensionCi')
accordingly, and delete the patch script.
*/
changeProject(uuid("d8ec7368-9cde-4a3c-b444-e7c3d06d247a")) {
    expectBuildTypesOrder(AbsoluteId("KafkaMonitoringExtensionCi_Build"), AbsoluteId("KafkaMonitoringExtensionCi_SetupKafka"), AbsoluteId("KafkaMonitoringExtensionCi_Stop"))
    buildTypesOrderIds = arrayListOf(AbsoluteId("KafkaMonitoringExtensionCi_Build"))
}
