package KafkaMonitoringExtensionCi.patches.projects


/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'd8ec7368-9cde-4a3c-b444-e7c3d06d247a' (id = 'KafkaMonitoringExtensionCi')
accordingly, and delete the patch script.
*/
