package KafkaMonitoringExtensionCi.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'e1e5435c-bcf9-456c-9b33-425fc5fd211c' (id = 'KafkaMonitoringExtensionCi')
accordingly, and delete the patch script.
*/
changeProject(uuid("e1e5435c-bcf9-456c-9b33-425fc5fd211c")) {
    params {
        add {
            text("APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY", "4c3eaeba-8115-44ef-89e7-80b0e3eed16a", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        }
    }

    expectBuildTypesOrder(AbsoluteId("KafkaMonitoringExtensionCi_Build"), AbsoluteId("KafkaMonitoringExtensionCi_SetupKafka"), AbsoluteId("KafkaMonitoringExtensionCi_Stop"))
    buildTypesOrderIds = arrayListOf(AbsoluteId("KafkaMonitoringExtensionCi_Build"))
}
