package KafkaMonitoringExtensionCi.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '0c296f0d-4bbb-4819-977c-a59555b0857a' (id = 'KafkaMonitoringExtensionCi_Build')
from your code, and delete the patch script.
*/
deleteBuildType(uuid("0c296f0d-4bbb-4819-977c-a59555b0857a"))

