package KafkaMonitoringExtensionCi.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '8b4bfba7-579b-49b7-b400-a00c1845ec66' (id = 'KafkaMonitoringExtensionCi_Build')
from your code, and delete the patch script.
*/
deleteBuildType(uuid("8b4bfba7-579b-49b7-b400-a00c1845ec66"))

