package KafkaMonitoringExtensionCi.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with uuid = '8d38ea0b-5554-4d51-9ca2-aa3897610fdb' (id = 'KafkaMonitoringExtensionCi_Build')
from your code, and delete the patch script.
*/
deleteBuildType(uuid("8d38ea0b-5554-4d51-9ca2-aa3897610fdb"))

