package ExtensionsJMX_KafkaMonitoringExtension.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '129f1153-3e0f-4794-a46b-8a1600da7692' (id = 'ExtensionsJMX_KafkaMonitoringExtension_SetupKafka')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("129f1153-3e0f-4794-a46b-8a1600da7692")) {
    params {
        expect {
            param("env.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY", "zxx907bb5f174b083cd4f6413203c259a5679287fefe33795f54430a4d0d6b0e47849de9b58c4b8a733")
        }
        update {
            param("env.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY", "credentialsJSON:65747919-6823-4341-8a84-db15e792b3d7")
        }
        expect {
            param("env.ENCRYPTION_KEY", "zxxc041dd7c481f14d0a252bd2c5d0100862acc6edf255b1ab7d553e0b306a6b630")
        }
        update {
            param("env.ENCRYPTION_KEY", "credentialsJSON:5c88d389-6725-4be7-a257-b4b03d0bac0b")
        }
        expect {
            param("env.PLAINTEXT_PWD", "zxx79a66a8da8b18181")
        }
        update {
            password("env.PLAINTEXT_PWD", "credentialsJSON:2423b6cf-3998-441f-a070-0ddc2256b8bd", display = ParameterDisplay.HIDDEN)
        }
    }
}
